[package]
name = "gbemu"
version = "0.1.0"
authors = ["Aleksi Luukkonen <aleksi@luukkonen.no>", "Knut Esten Melandsø Nekså"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
